/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarRouteImport } from './routes/car'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriversSlugRouteImport } from './routes/drivers.$slug'

const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRoute = CarRouteImport.update({
  id: '/car',
  path: '/car',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversSlugRoute = DriversSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DriversRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/car': typeof CarRoute
  '/contact': typeof ContactRoute
  '/drivers': typeof DriversRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/performance': typeof PerformanceRoute
  '/drivers/$slug': typeof DriversSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/car': typeof CarRoute
  '/contact': typeof ContactRoute
  '/drivers': typeof DriversRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/performance': typeof PerformanceRoute
  '/drivers/$slug': typeof DriversSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/car': typeof CarRoute
  '/contact': typeof ContactRoute
  '/drivers': typeof DriversRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/performance': typeof PerformanceRoute
  '/drivers/$slug': typeof DriversSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/car'
    | '/contact'
    | '/drivers'
    | '/gallery'
    | '/performance'
    | '/drivers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/car'
    | '/contact'
    | '/drivers'
    | '/gallery'
    | '/performance'
    | '/drivers/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/car'
    | '/contact'
    | '/drivers'
    | '/gallery'
    | '/performance'
    | '/drivers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CarRoute: typeof CarRoute
  ContactRoute: typeof ContactRoute
  DriversRoute: typeof DriversRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  PerformanceRoute: typeof PerformanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car': {
      id: '/car'
      path: '/car'
      fullPath: '/car'
      preLoaderRoute: typeof CarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/$slug': {
      id: '/drivers/$slug'
      path: '/$slug'
      fullPath: '/drivers/$slug'
      preLoaderRoute: typeof DriversSlugRouteImport
      parentRoute: typeof DriversRoute
    }
  }
}

interface DriversRouteChildren {
  DriversSlugRoute: typeof DriversSlugRoute
}

const DriversRouteChildren: DriversRouteChildren = {
  DriversSlugRoute: DriversSlugRoute,
}

const DriversRouteWithChildren =
  DriversRoute._addFileChildren(DriversRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CarRoute: CarRoute,
  ContactRoute: ContactRoute,
  DriversRoute: DriversRouteWithChildren,
  GalleryRoute: GalleryRoute,
  PerformanceRoute: PerformanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
